// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/example2/example2.proto

package go_micro_srv_example2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example2 service

type Example2Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Example2_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Example2_PingPongService, error)
}

type example2Service struct {
	c    client.Client
	name string
}

func NewExample2Service(name string, c client.Client) Example2Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.example2"
	}
	return &example2Service{
		c:    c,
		name: name,
	}
}

func (c *example2Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Example2.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *example2Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Example2_StreamService, error) {
	req := c.c.NewRequest(c.name, "Example2.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &example2ServiceStream{stream}, nil
}

type Example2_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type example2ServiceStream struct {
	stream client.Stream
}

func (x *example2ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *example2ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *example2ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *example2ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *example2Service) PingPong(ctx context.Context, opts ...client.CallOption) (Example2_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Example2.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &example2ServicePingPong{stream}, nil
}

type Example2_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type example2ServicePingPong struct {
	stream client.Stream
}

func (x *example2ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *example2ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *example2ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *example2ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *example2ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Example2 service

type Example2Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Example2_StreamStream) error
	PingPong(context.Context, Example2_PingPongStream) error
}

func RegisterExample2Handler(s server.Server, hdlr Example2Handler, opts ...server.HandlerOption) error {
	type example2 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Example2 struct {
		example2
	}
	h := &example2Handler{hdlr}
	return s.Handle(s.NewHandler(&Example2{h}, opts...))
}

type example2Handler struct {
	Example2Handler
}

func (h *example2Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Example2Handler.Call(ctx, in, out)
}

func (h *example2Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Example2Handler.Stream(ctx, m, &example2StreamStream{stream})
}

type Example2_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type example2StreamStream struct {
	stream server.Stream
}

func (x *example2StreamStream) Close() error {
	return x.stream.Close()
}

func (x *example2StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *example2StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *example2StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *example2Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Example2Handler.PingPong(ctx, &example2PingPongStream{stream})
}

type Example2_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type example2PingPongStream struct {
	stream server.Stream
}

func (x *example2PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *example2PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *example2PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *example2PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *example2PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
